import { library } from '@fortawesome/fontawesome-svg-core'

// light icons
import {
  faTicketAlt as falTicketAlt,
  faUsers as falUsers,
  faChartBar as falChartBar,
  faPuzzlePiece as falPuzzlePiece,
  faBook as falBook,
  faCog as falCog,
  faQuestionCircle as falQuestionCircle,
  faBell as falBell,
  faInboxIn as falInboxIn,
  faInbox as falInbox,
  faShoppingCart as falShoppingCart,
  faPlus as falPlus,
  faEllipsisH as falEllipsisH,
  faEnvelope as falEnvelope,
  faKey as falKey,
  faUser as falUser,
  faMobileAndroidAlt as falMobileAndroidAlt,
  faSearch as falSearch,
  faTimes as falTimes,
  faArrowLeft as falArrowLeft,
  faMehBlank as falMehBlank,
  faSmile as falSmile,
  faMeh as falMeh,
  faFrown as falFrown,
} from '@fortawesome/pro-light-svg-icons'

// solid icons
import {
  faBolt as fasBolt,
  faTicketAlt as fasTicketAlt,
  faUsers as fasUsers,
  faChartBar as fasChartBar,
  faPuzzlePiece as fasPuzzlePiece,
  faBook as fasBook,
  faCog as fasCog,
  faSquare as fasSquare,
  faCheckSquare as fasCheckSquare,
  faCheckCircle as fasCheckCircle,
  faCaretDown as fasCaretDown,
  faExclamationTriangle as fasExclamationTriangle,
  faCreditCardFront as fascreditCardFront,
  faBars as fasBars,
} from '@fortawesome/pro-solid-svg-icons'

// regular icons
import {
  faPlus as farPlus,
  faChevronLeft as farChevronLeft,
  faChevronRight as farChevronRight,
  faChevronDown as farChevronDown,
  faExclamationTriangle as farExclamationTriangle,
  faBullseyeArrow as farBullseyeArrow,
  faEye as farEye,
  faEyeSlash as farEyeSlash,
  faCalendarDay as farCalendarDay,
  faGlobe as farGlobe,
  faBuilding as farBuilding,
  faSquare as farSquare,
  faSlidersHSquare as farSlidersHSquare,
  faArrowLeft as farArrowLeft,
  faMehBlank as farMehBlank,
  faSmile as farSmile,
  faMeh as farMeh,
  faFrown as farFrown,
  faTimes as farTimes,
} from '@fortawesome/pro-regular-svg-icons'

// brands
import {
  faFacebookSquare,
  faInstagram,
} from '@fortawesome/free-brands-svg-icons'

library.add(
  falTicketAlt,
  fasTicketAlt,
  falUsers,
  fasUsers,
  falChartBar,
  fasChartBar,
  falPuzzlePiece,
  fasPuzzlePiece,
  falBook,
  fasBook,
  falCog,
  fasCog,
  falQuestionCircle,
  falBell,
  fasBolt,
  falInboxIn,
  falInbox,
  falShoppingCart,
  falPlus,
  farPlus,
  faFacebookSquare,
  faInstagram,
  falEllipsisH,
  falEnvelope,
  falKey,
  falUser,
  falMobileAndroidAlt,
  falSearch,
  farChevronLeft,
  farChevronRight,
  farChevronDown,
  fasSquare,
  farSquare,
  fasCheckSquare,
  fasCheckCircle,
  fasCaretDown,
  falTimes,
  farTimes,
  falArrowLeft,
  farArrowLeft,
  falMehBlank,
  farMehBlank,
  falSmile,
  farSmile,
  falMeh,
  farMeh,
  falFrown,
  farFrown,
  fasExclamationTriangle,
  farExclamationTriangle,
  farBullseyeArrow,
  farEye,
  farEyeSlash,
  farCalendarDay,
  farGlobe,
  farBuilding,
  fascreditCardFront,
  farCalendarDay,
  fasBars,
  farSlidersHSquare
)
